FROM flemay/musketeers@sha256:a23e681cf1ad72b56f513d15b10a1e5b20a5d2d36f2438121e9c88aefebb3e55
# ARG AWSCLI2=https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
RUN pip install awscli

ENTRYPOINT [ "/bin/bash" ]