version: "3.8"

services:
  aws:
    image: amazon/aws-cli:2.0.36
    volumes:
      - ${PWD}:/app
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    entrypoint:
      - aws
    
  ci-terraform:
    image: hashicorp/terraform:0.12.29
    working_dir: /tf
    volumes:
      - ${PWD}/tf:/tf
      - ../.github/terraform:/root/.terraform.d
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - TF_IN_AUTOMATION=yes