version: "3.8"

services:
  gh:
    image: github-actions
    build:
      dockerfile: ./docker/Dockerfile
      context: .

  aws:
    image: amazon/aws-cli:2.0.36
    volumes:
      - ${PWD}:/app
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    entrypoint:
      - aws