name: on-push-main-ci-tf-apply

on:
  push:
    branches:
      - master
    paths:
      - ci/tf/**/*

jobs:
  tf-apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: bluwy/substitute-string-action@v1
        id: tf_cred
        with:
          _input-file: './.github/terraform/credentials.tfrc.json'
          TERRAFORM_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}

      - name: Update Terraform Credentials
        run: echo '${{ steps.tf_cred.outputs.result }}' > ./.github/terraform/credentials.tfrc.json

      - name: Terraform Apply
        working-directory: ci
        run: make tf-ci-apply
